tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#2b2c2c",
        "surface-container-low": "#131313",
        "surface-container-lowest": "#000000",
        "on-surface-variant": "#acabaa",
        "on-secondary-fixed": "#3d3f44",
        "on-tertiary-fixed": "#393c55",
        "primary-fixed-dim": "#bbd6ff",
        "on-primary-container": "#b4d2ff",
        "on-primary-fixed-variant": "#005da5",
        "secondary-dim": "#9c9ea4",
        "error": "#ee7d77",
        "error-dim": "#bb5551",
        "inverse-primary": "#0061ab",
        "tertiary-dim": "#cecfef",
        "surface": "#0e0e0e",
        "surface-variant": "#252626",
        "tertiary-container": "#dcddfe",
        "tertiary": "#edecff",
        "tertiary-fixed": "#dcddfe",
        "on-surface": "#e7e5e5",
        "secondary": "#9c9ea4",
        "on-secondary-fixed-variant": "#595b61",
        "surface-tint": "#a2c9ff",
        "surface-dim": "#0e0e0e",
        "inverse-surface": "#fcf9f8",
        "on-error-container": "#ff9993",
        "tertiary-fixed-dim": "#cecfef",
        "on-tertiary-fixed-variant": "#555873",
        "on-secondary-container": "#bdbfc5",
        "secondary-fixed": "#e1e2e8",
        "on-secondary": "#1e2025",
        "outline-variant": "#484848",
        "background": "#0e0e0e",
        "on-error": "#490106",
        "on-tertiary-container": "#4c4e69",
        "on-primary": "#004176",
        "primary": "#a2c9ff",
        "outline": "#767575",
        "on-tertiary": "#545671",
        "on-primary-fixed": "#004075",
        "secondary-container": "#393b40",
        "primary-dim": "#88bcff",
        "surface-container-highest": "#252626",
        "inverse-on-surface": "#565555",
        "surface-container-high": "#1f2020",
        "surface-container": "#191a1a",
        "primary-fixed": "#d3e4ff",
        "error-container": "#7f2927",
        "on-background": "#e7e5e5",
        "secondary-fixed-dim": "#d3d4da",
        "primary-container": "#004882"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
}
